# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: CI

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.5', '3.6', '3.7', '3.8', '3.9', '3.10']
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install system dependencies
      run: |
        sudo apt-get install -y graphviz idle python3-matplotlib
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip wheel
        pip install Sphinx recommonmark pycodestyle coverage coveralls numpy mypy
    - name: Test
      run: |
        python -Wall setup.py try
        python setup.py install
        python -Wall setup.py test
        COVERAGE=1 coverage run test/runtest.py
        python run.py --doctest
    - name: Lint
      run: |
        pycodestyle pympler
    - name: Type checks
      run: |
        mypy pympler
    - name: Build documentation
      run: |
        python run.py --html
